name: Publish Python distributions to PyPI

on: push

jobs:
  build-n-publish:
    name: Publish Python distributions to PyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.8
    - name: Install wheel
      run: >-
        python -m
        pip install
        wheel
        setuptools
        --user
    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      continue-on-error: true
      with:
        password: ${{ secrets.TEST_PYPI_PASSWORD }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
